INSERT INTO tutorial (id,description,published,title) VALUES (default,'Andra Pradesh', 1,'Hyderabad')
,(default,'Arunachal Pradesh',0,'Itangar')
,(default,'Assam',1,'Dispur')
,(default,'Bihar',0,'Patna')
,(default,'Chhattisgarh',1,'Raipur')
,(default,'Goa',0,'Panaji')
,(default,'Gujarat',1,'Gandhinagar')
,(default,'Haryana',0,'Chandigarh')
,(default,'Himachal Pradesh',1,'Shimla')
,(default,'Jharkhand',0,'Ranchi')
,(default,'Karnataka',1,'Bangalore')
,(default,'Kerala',0,'Thiruvananthapuram')
,(default,'Madhya Pradesh',1,'Bhopal')
,(default,'Maharashtra',0,'Mumbai')
,(default,'Manipur',1,'Imphal')
,(default,'Meghalaya',0,'Shillong')
,(default,'Mizoram',1,'Aizawi')
,(default,'Nagaland',0,'Kohima')
,(default,'Orissa',1,'Bhubaneshwar')
,(default,'Rajasthan',0,'Jaipur')
,(default,'Sikkim',1,'Gangtok')
,(default,'Tamil Nadu',0,'Chennai')
,(default,'Telangana',1,'Hyderabad')
,(default,'Tripura',0,'Agartala')
,(default,'Uttaranchal',1,'Dehradun')
,(default,'Uttar Pradesh',0,'Lucknow')
,(default,'West Bengal',1,'Kolkata')
,(default,'Punjab',0,'Chandigarh')
,(default,'Harding Trujillo',0,'Gravida Corporation')
,(default,'Salvador Merritt',1,'Natoque Penatibus Et Incorporated')
,(default,'Demetrius Hull',1,'Nisl Nulla Industries')
,(default,'Ralph Morse',0,'Neque Inc.')
,(default,'Cole Payne',0,'Dapibus Quam Quis LLP')
,(default,'Zephania Mcneil',0,'Tempor Industries')
,(default,'Kareem Oliver',0,'Eu Ltd')
,(default,'Nathan Moran',0,'Nulla Inc.')
,(default,'Perry Bray',1,'Nam Consequat Dolor Foundation')
,(default,'Paul Mcconnell',0,'Et Libero Associates')
,(default,'Jack Oneill',1,'Lorem Limited')
,(default,'Derek Garner',1,'Feugiat Sed Nec Foundation')
,(default,'Dalton Riggs',1,'Blandit Company')
,(default,'Upton Dean',0,'Dapibus Gravida Aliquam Foundation')
,(default,'Ishmael Jones',1,'Volutpat Nulla LLC')
,(default,'Samson Owen',1,'Lectus Institute')
,(default,'Chase Lowery',1,'Ornare Corporation')
,(default,'Julian Fleming',1,'Mi LLP')
,(default,'Avram Pollard',1,'Aliquet Lobortis Nisi Foundation')
,(default,'Wing Boyle',0,'Mattis Foundation')
,(default,'Jermaine Rojas',0,'Aliquam Adipiscing Ltd')
,(default,'Chadwick Harris',1,'Tristique Senectus Et Associates')
,(default,'Nash Vaughan',1,'Sociosqu LLC')
,(default,'Lamar Best',1,'Etiam Vestibulum LLP')
,(default,'Adrian Valenzuela',0,'Sem Consulting')
,(default,'Reese Powers',1,'Vel Company')
,(default,'Robert Wallace',1,'Orci Ut Inc.')
,(default,'Aquila Crawford',1,'Ac Arcu Nunc Consulting')
,(default,'Craig Chavez',0,'Augue Malesuada Malesuada Industries')
,(default,'Ishmael Dominguez',1,'Lobortis Consulting')
,(default,'Adam Larson',1,'In LLP')
,(default,'Tanek Brown',0,'Turpis Egestas Aliquam PC')
,(default,'Kasper Baird',0,'Dictum Augue Malesuada Ltd')
,(default,'Damon Durham',0,'Adipiscing Lobortis Risus Limited')
,(default,'Xanthus Charles',0,'Lectus Pede Ultrices LLP')
,(default,'Tyrone Mcguire',0,'Ornare LLC')
,(default,'Cody Hewitt',0,'Ac Facilisis Facilisis Institute')
,(default,'Colton Waters',1,'Sed Incorporated')
,(default,'Thaddeus Acosta',0,'Vitae Sodales LLP')
,(default,'Wyatt Hancock',1,'Vitae Limited')
,(default,'Harding Trujillo',1,'Iaculis Lacus Consulting')
,(default,'Dennis Hicks',0,'Mauris Associates')
,(default,'Aidan Miller',0,'Dolor Corp.')
,(default,'John Henson',0,'In Magna Phasellus Corporation')
,(default,'Steven Abbott',1,'Nulla Magna Institute')
,(default,'Nero Mitchell',0,'Nulla Interdum Corp.')
,(default,'Abdul Wyatt',0,'A Limited')
,(default,'Jeremy Blanchard',1,'Pharetra Sed Hendrerit Inc.')
,(default,'Garrett Spencer',1,'Neque Foundation')
,(default,'Evan Cameron',1,'Elit Dictum Eu Consulting')
,(default,'Flynn Preston',1,'Enim Consequat Purus Company')
,(default,'Jarrod Nichols',0,'Enim Sit Amet LLC')
,(default,'Chancellor Rivers',1,'Non Dui Nec Inc.')
,(default,'Marsden Diaz',0,'Condimentum Donec Ltd')
,(default,'Graiden Strickland',1,'At Consulting')
,(default,'Channing Suarez',1,'Mauris Morbi Consulting')
,(default,'Garrett Giles',0,'Congue Associates')
,(default,'Cooper Rowe',0,'Mi Ac Incorporated')
,(default,'Kenneth Patrick',0,'Orci Luctus Institute')
,(default,'Mohammad Dixon',0,'Convallis Institute')
,(default,'Coby Horton',1,'Nec PC')
,(default,'Vaughan Keller',1,'Ac Fermentum Vel Corp.')
,(default,'Jack Mclean',0,'Lobortis Industries')
,(default,'Ray Richmond',0,'Ipsum Corp.')
,(default,'Branden Keller',1,'Fames LLP')
,(default,'Brady Terry',0,'Amet Nulla Donec Consulting')
,(default,'Kenyon Scott',0,'Quis Tristique Ac Ltd')
,(default,'Marvin Yang',1,'Rhoncus Industries')
,(default,'Prescott Rice',1,'Suspendisse Dui Industries')
,(default,'Jerome Leon',1,'Curabitur LLC')
,(default,'Myles Frye',1,'Lorem Ut Aliquam PC')
,(default,'Kenyon Blevins',0,'Donec Limited')
,(default,'Graham Mckee',1,'Nec Euismod Inc.')
,(default,'Cade Bush',0,'Magna Malesuada Company')
,(default,'Dominic Morris',1,'Volutpat Nunc LLP')
,(default,'Blaze Carlson',1,'Luctus PC')
,(default,'Hamish Barnes',0,'Sem Vitae Aliquam Corporation')
,(default,'Kyle Griffith',1,'Augue Ut Industries')
,(default,'Brendan Booker',1,'Mauris Sapien Cursus Foundation')
,(default,'Flynn Buckley',0,'Magna A Tortor Inc.')
,(default,'Todd Mcmillan',1,'Arcu Company')
,(default,'Honorato Hensley',1,'Amet Nulla Inc.')
,(default,'Brandon Dyer',1,'Metus Vivamus Euismod LLC')
,(default,'Damian Bentley',1,'Et Rutrum Non LLP')
,(default,'Fitzgerald Charles',1,'Faucibus Leo Company')
,(default,'Avram Santana',0,'Fringilla Est Incorporated')
,(default,'Baxter Poole',0,'Laoreet Libero Et Industries')
,(default,'Lyle Mcleod',0,'Eget Industries')
,(default,'Jeremy Guerrero',1,'Aliquet Libero Integer Foundation')
,(default,'Kasper Snyder',0,'Tellus Eu Augue Inc.')
,(default,'Timon Christian',0,'Neque Sed Associates')
,(default,'Kane Chen',0,'Gravida Sagittis Associates')
,(default,'Hedley Hogan',0,'Aliquet Ltd')
,(default,'Nissim Burch',0,'Leo Ltd')
,(default,'Ashton Carson',0,'Semper Egestas Urna LLP')
,(default,'James Garrett',1,'Donec Vitae Foundation')
,(default,'Beau Burton',0,'Eget Magna Foundation')
,(default,'Kamal Gardner',0,'Enim Mi Consulting')
,(default,'Porter Walker',1,'Metus In Consulting')
,(default,'Daniel Melton',0,'Mollis Integer Tincidunt Corp.');

INSERT INTO student (id,name) VALUES (default,'Tom')
,(default,'Nick')
,(default,'Ed')
,(default,'Bette')
,(default,'Grace')
,(default,'Matthew')
,(default,'Joe')
,(default,'Christian')
,(default,'Karl')
,(default,'Uma')
,(default,'Vivien')
,(default,'Cuba')
,(default,'Stewart')
,(default,'Callie')
,(default,'Raphael')
,(default,'Charles')
,(default,'Ariel')
,(default,'Kenyon')
,(default,'Isaac')
,(default,'Hayfa')
,(default,'Sandra')
,(default,'Pamela')
,(default,'Judah')
,(default,'Marsden')
,(default,'Abbot')
,(default,'Winter')
,(default,'Hammett')
,(default,'Chava')
,(default,'Athena')
,(default,'Roth')
,(default,'Nayda')
,(default,'Carson')
,(default,'Zephania')
,(default,'Britanney')
,(default,'Oleg')
,(default,'Denton')
,(default,'Ruth')
,(default,'Kerry')
,(default,'Zane')
,(default,'Blake')
,(default,'Tobias')
,(default,'Donovan')
,(default,'Genevieve')
,(default,'Norman')
,(default,'Gage')
,(default,'Tatum')
,(default,'Melanie')
,(default,'Clinton')
,(default,'Rooney')
,(default,'Flynn')
,(default,'Lenore')
,(default,'Samuel')
,(default,'Quinn')
,(default,'Hyacinth')
,(default,'Kylee')
,(default,'Flynn')
,(default,'Marcia')
,(default,'Evan')
,(default,'Quincy')
,(default,'Lael')
,(default,'Daniel')
,(default,'Levi')
,(default,'Xander')
,(default,'Reed')
,(default,'Desirae')
,(default,'Germane')
,(default,'Myra')
,(default,'Ivor')
,(default,'Nichole')
,(default,'Hashim')
,(default,'Tyrone')
,(default,'Merritt')
,(default,'Noel')
,(default,'Harlan')
,(default,'Quail')
,(default,'Hanna')
,(default,'Hunter')
,(default,'Irene')
,(default,'Vera')
,(default,'Cade')
,(default,'Imelda')
,(default,'Ashely')
,(default,'Shafira')
,(default,'Aimee')
,(default,'Madaline')
,(default,'Velma')
,(default,'Yoshio')
,(default,'Sybill')
,(default,'Minerva')
,(default,'Fletcher')
,(default,'Xyla')
,(default,'Zane')
,(default,'Karleigh')
,(default,'Quyn')
,(default,'Henry')
,(default,'Tatum')
,(default,'Tyrone')
,(default,'Eagan')
,(default,'Nyssa')
,(default,'Duncan')
,(default,'Daryl')
,(default,'Kevin')
,(default,'Imelda')
,(default,'Priscilla')
,(default,'Grace')
,(default,'Kerry')
,(default,'Aileen')
,(default,'Steven')
,(default,'Ezra')
,(default,'Garrett')
,(default,'Lacy')
,(default,'Sydney')
,(default,'Ramy')
,(default,'Karim')
,(default,'Tamer');



INSERT INTO tutorial_student (tutorial_id,student_id) VALUES (1,1)
,(1,2)
,(1,3)
,(1,4)
,(1,5)
,(1,6)
,(1,7)
,(1,8)
,(1,9)
,(1,10)
,(1,11)
,(1,12)
,(1,13)
,(1,14)
,(1,15)
,(1,16)
,(1,17)
,(1,18)
,(1,19)
,(1,20)
,(1,21)
,(1,22)
,(1,23)
,(1,24)
,(1,25)
,(1,26)
,(1,27)
,(1,28)
,(1,29)
,(1,30)
,(1,31)
,(1,32)
,(1,33)
,(1,34)
,(1,35)
,(1,36)
,(1,37)
,(1,38)
,(1,39)
,(1,40)
,(1,41)
,(1,42)
,(1,43)
,(1,44)
,(1,45)
,(1,46)
,(1,47)
,(1,48)
,(1,49)
,(1,50)
,(1,51)
,(1,52)
,(1,53)
,(1,54)
,(1,55)
,(1,56)
,(1,57)
,(1,58)
,(1,59)
,(1,60)
,(1,61)
,(1,62)
,(1,63)
,(1,64)
,(1,65)
,(1,66)
,(1,67)
,(1,68)
,(1,69)
,(1,70)
,(1,71)
,(1,72)
,(1,73)
,(1,74)
,(1,75)
,(1,76)
,(1,77)
,(1,78)
,(1,79)
,(1,80)
,(1,81)
,(1,82)
,(1,83)
,(1,84)
,(1,85)
,(1,86)
,(1,87)
,(1,88)
,(1,89)
,(1,90)
,(1,91)
,(1,92)
,(1,93)
,(1,94)
,(1,95)
,(1,96)
,(1,97)
,(1,98)
,(1,99)
,(1,100);