INSERT INTO tutorial VALUES (default,'Andra Pradesh', 1,'Hyderabad');
INSERT INTO tutorial VALUES (default,'Arunachal Pradesh',0,'Itangar');
INSERT INTO tutorial VALUES (default,'Assam',1,'Dispur');
INSERT INTO tutorial VALUES (default,'Bihar',0,'Patna');
INSERT INTO tutorial VALUES (default,'Chhattisgarh',1,'Raipur');
INSERT INTO tutorial VALUES (default,'Goa',0,'Panaji');
INSERT INTO tutorial VALUES (default,'Gujarat',1,'Gandhinagar');
INSERT INTO tutorial VALUES (default,'Haryana',0,'Chandigarh');
INSERT INTO tutorial VALUES (default,'Himachal Pradesh',1,'Shimla');
INSERT INTO tutorial VALUES (default,'Jharkhand',0,'Ranchi');
INSERT INTO tutorial VALUES (default,'Karnataka',1,'Bangalore');
INSERT INTO tutorial VALUES (default,'Kerala',0,'Thiruvananthapuram');
INSERT INTO tutorial VALUES (default,'Madhya Pradesh',1,'Bhopal');
INSERT INTO tutorial VALUES (default,'Maharashtra',0,'Mumbai');
INSERT INTO tutorial VALUES (default,'Manipur',1,'Imphal');
INSERT INTO tutorial VALUES (default,'Meghalaya',0,'Shillong');
INSERT INTO tutorial VALUES (default,'Mizoram',1,'Aizawi');
INSERT INTO tutorial VALUES (default,'Nagaland',0,'Kohima');
INSERT INTO tutorial VALUES (default,'Orissa',1,'Bhubaneshwar');
INSERT INTO tutorial VALUES (default,'Rajasthan',0,'Jaipur');
INSERT INTO tutorial VALUES (default,'Sikkim',1,'Gangtok');
INSERT INTO tutorial VALUES (default,'Tamil Nadu',0,'Chennai');
INSERT INTO tutorial VALUES (default,'Telangana',1,'Hyderabad');
INSERT INTO tutorial VALUES (default,'Tripura',0,'Agartala');
INSERT INTO tutorial VALUES (default,'Uttaranchal',1,'Dehradun');
INSERT INTO tutorial VALUES (default,'Uttar Pradesh',0,'Lucknow');
INSERT INTO tutorial VALUES (default,'West Bengal',1,'Kolkata');
INSERT INTO tutorial VALUES (default,'Punjab',0,'Chandigarh');